// Source code is unavailable, and was generated by the Fernflower decompiler.
package com.reigninblood.TaleMon_PokeBall.interactions;

import com.hypixel.hytale.codec.builder.BuilderCodec;
import com.hypixel.hytale.codec.builder.BuilderCodec.Builder;
import com.hypixel.hytale.component.CommandBuffer;
import com.hypixel.hytale.component.Ref;
import com.hypixel.hytale.function.consumer.TriConsumer;
import com.hypixel.hytale.logger.HytaleLogger;
import com.hypixel.hytale.math.vector.Vector3d;
import com.hypixel.hytale.math.vector.Vector3f;
import com.hypixel.hytale.protocol.BlockPosition;
import com.hypixel.hytale.protocol.InteractionState;
import com.hypixel.hytale.protocol.InteractionType;
import com.hypixel.hytale.server.core.asset.type.blocktype.config.BlockFace;
import com.hypixel.hytale.server.core.asset.type.model.config.Model;
import com.hypixel.hytale.server.core.entity.Entity;
import com.hypixel.hytale.server.core.entity.EntityUtils;
import com.hypixel.hytale.server.core.entity.InteractionContext;
import com.hypixel.hytale.server.core.entity.LivingEntity;
import com.hypixel.hytale.server.core.entity.entities.Player;
import com.hypixel.hytale.server.core.inventory.ItemStack;
import com.hypixel.hytale.server.core.modules.interaction.interaction.CooldownHandler;
import com.hypixel.hytale.server.core.modules.interaction.interaction.config.SimpleInstantInteraction;
import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;
import com.hypixel.hytale.server.npc.NPCPlugin;
import com.hypixel.hytale.server.npc.metadata.CapturedNPCMetadata;
import com.reigninblood.TaleMon_PokeBall.util.ConsumeUtil;

import java.util.concurrent.CompletableFuture;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import javax.annotation.Nonnull;

public class PokeBallReleaseInteraction extends SimpleInstantInteraction {
    public static final String ID = "talemon:pokeball_release";
    public static final BuilderCodec<PokeBallReleaseInteraction> CODEC;

    // ✅ delay demandé
    private static final long RELEASE_DELAY_MS = 1000L;

    public PokeBallReleaseInteraction(String id) {
        super(id);
    }

    protected PokeBallReleaseInteraction() {
        super("talemon:pokeball_release");
    }

    protected void firstRun(@Nonnull InteractionType type, @Nonnull InteractionContext context, @Nonnull CooldownHandler cooldownHandler) {
        // ✅ CAPTURE TOUT CE QUI RESTE VALIDE AVANT LE DELAY
        final CommandBuffer<EntityStore> buffer = context.getCommandBuffer();
        if (buffer == null) {
            context.getState().state = InteractionState.Failed;
            return;
        }

        final ItemStack held = context.getHeldItem();
        if (held == null || held.isEmpty()) {
            context.getState().state = InteractionState.Failed;
            return;
        }

        final Ref<EntityStore> playerRef = context.getEntity();
        final Entity ent = EntityUtils.getEntity(playerRef, buffer);
        if (!(ent instanceof LivingEntity)) {
            context.getState().state = InteractionState.Failed;
            return;
        }

        final LivingEntity living = (LivingEntity)ent;
        if (!(living instanceof Player)) {
            context.getState().state = InteractionState.Failed;
            return;
        }

        final Player player = (Player)living;

        final CapturedNPCMetadata meta = (CapturedNPCMetadata)held.getFromMetadataOrNull("CapturedEntity", CapturedNPCMetadata.CODEC);
        if (meta == null) {
            HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] RELEASE_FAIL no CapturedEntity metadata");
            context.getState().state = InteractionState.Failed;
            return;
        }

        final BlockPosition target = context.getTargetBlock();
        if (target == null) {
            context.getState().state = InteractionState.Failed;
            return;
        }

        Vector3d spawnPos = new Vector3d((double)target.x + 0.5D, (double)target.y + 0.5D, (double)target.z + 0.5D);
        BlockFace face = null;
        if (context.getClientState() != null) {
            face = BlockFace.fromProtocolFace(context.getClientState().blockFace);
        }

        // Même logique que ton fichier actuel
        if (face != null) {
            Vector3d dir = new Vector3d(face.getDirection());
            spawnPos.add(dir);
            spawnPos.y = (double)target.y + 1.01D;
        } else {
            spawnPos.y = (double)target.y + 1.01D;
        }

        spawnPos.x += 0.01D;
        spawnPos.z += 0.01D;

        final Vector3d finalSpawnPos = spawnPos;
        final int roleIndex = meta.getRoleIndex();
        final String nameKey = meta.getNpcNameKey();
        final NPCPlugin npcPlugin = NPCPlugin.get();

        HytaleLogger.getLogger().at(Level.INFO).log(
                "[TaleMon_PokeBall] RELEASE_USE delay=%sms roleIndex=%s npc=%s pos=%s face=%s",
                RELEASE_DELAY_MS, roleIndex, nameKey, finalSpawnPos, face == null ? "null" : face.name()
        );

        // ✅ IMPORTANT :
        // On ne touche PLUS au context après 1 seconde.
        // On exécute spawn + consume via buffer.run (serveur thread) APRES le délai.
        CompletableFuture.runAsync(() -> {
            buffer.run((store) -> {
                try {
                    npcPlugin.spawnEntity(store, roleIndex, finalSpawnPos, Vector3f.ZERO, (Model)null, (TriConsumer)null);
                } catch (Throwable t) {
                    HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] RELEASE_FAIL spawn exception=%s", String.valueOf(t));
                    return;
                }

                boolean consumed = false;
                try {
                    consumed = ConsumeUtil.consumeActiveHotbarItem(player, held);
                } catch (Throwable t) {
                    HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] RELEASE_FAIL consume exception=%s", String.valueOf(t));
                }

                HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] RELEASE_OK spawned=true consume ok=%s", consumed);
            });
        }, CompletableFuture.delayedExecutor(RELEASE_DELAY_MS, TimeUnit.MILLISECONDS));

        // Interaction finie tout de suite (on laisse le serveur faire le reste)
        context.getState().state = InteractionState.Finished;
    }

    static {
        CODEC = ((Builder)BuilderCodec.builder(PokeBallReleaseInteraction.class, PokeBallReleaseInteraction::new, SimpleInstantInteraction.CODEC).documentation("Release a captured NPC from a Pok\u00e9Ball (consumes the ball).")).build();
    }
}
