// Source code is unavailable, and was generated by the Fernflower decompiler.
package com.reigninblood.TaleMon_PokeBall.interactions;

import com.hypixel.hytale.codec.builder.BuilderCodec;
import com.hypixel.hytale.codec.builder.BuilderCodec.Builder;
import com.hypixel.hytale.component.CommandBuffer;
import com.hypixel.hytale.component.Ref;
import com.hypixel.hytale.function.consumer.TriConsumer;
import com.hypixel.hytale.logger.HytaleLogger;
import com.hypixel.hytale.math.vector.Vector3d;
import com.hypixel.hytale.math.vector.Vector3f;
import com.hypixel.hytale.protocol.BlockPosition;
import com.hypixel.hytale.protocol.InteractionState;
import com.hypixel.hytale.protocol.InteractionType;
import com.hypixel.hytale.server.core.asset.type.blocktype.config.BlockFace;
import com.hypixel.hytale.server.core.asset.type.model.config.Model;
import com.hypixel.hytale.server.core.entity.Entity;
import com.hypixel.hytale.server.core.entity.EntityUtils;
import com.hypixel.hytale.server.core.entity.InteractionContext;
import com.hypixel.hytale.server.core.entity.LivingEntity;
import com.hypixel.hytale.server.core.entity.entities.Player;
import com.hypixel.hytale.server.core.inventory.ItemStack;
import com.hypixel.hytale.server.core.modules.interaction.interaction.CooldownHandler;
import com.hypixel.hytale.server.core.modules.interaction.interaction.config.SimpleInstantInteraction;
import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;
import com.hypixel.hytale.server.npc.NPCPlugin;
import com.hypixel.hytale.server.npc.metadata.CapturedNPCMetadata;
import com.reigninblood.TaleMon_PokeBall.util.ConsumeUtil;
import java.util.logging.Level;
import javax.annotation.Nonnull;

public class PokeBallReleaseInteraction extends SimpleInstantInteraction {
    public static final String ID = "talemon:pokeball_release";
    public static final BuilderCodec<PokeBallReleaseInteraction> CODEC;

    public PokeBallReleaseInteraction(String id) {
        super(id);
    }

    protected PokeBallReleaseInteraction() {
        super("talemon:pokeball_release");
    }

    protected void firstRun(@Nonnull InteractionType type, @Nonnull InteractionContext context, @Nonnull CooldownHandler cooldownHandler) {
        CommandBuffer<EntityStore> buffer = context.getCommandBuffer();
        if (buffer == null) {
            context.getState().state = InteractionState.Failed;
        } else {
            ItemStack held = context.getHeldItem();
            if (held != null && !held.isEmpty()) {
                Ref<EntityStore> playerRef = context.getEntity();
                Entity ent = EntityUtils.getEntity(playerRef, buffer);
                if (ent instanceof LivingEntity) {
                    LivingEntity living = (LivingEntity)ent;
                    if (living instanceof Player) {
                        Player player = (Player)living;
                        CapturedNPCMetadata meta = (CapturedNPCMetadata)held.getFromMetadataOrNull("CapturedEntity", CapturedNPCMetadata.CODEC);
                        if (meta == null) {
                            HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] RELEASE_FAIL no CapturedEntity metadata");
                            context.getState().state = InteractionState.Failed;
                            return;
                        }

                        BlockPosition target = context.getTargetBlock();
                        if (target == null) {
                            context.getState().state = InteractionState.Failed;
                            return;
                        }

                        Vector3d spawnPos = new Vector3d((double)target.x + 0.5D, (double)target.y + 0.5D, (double)target.z + 0.5D);
                        BlockFace face = null;
                        if (context.getClientState() != null) {
                            face = BlockFace.fromProtocolFace(context.getClientState().blockFace);
                        }

                        double EPS = 0.01D;
                        if (face != null) {
                            Vector3d dir = new Vector3d(face.getDirection());
                            spawnPos.add(dir);
                            if (face == BlockFace.UP) {
                                spawnPos.y = (double)target.y + 1.01D;
                            } else {
                                spawnPos.y = (double)target.y + 1.01D;
                            }
                        } else {
                            spawnPos.y = (double)target.y + 1.01D;
                        }

                        spawnPos.x += 0.01D;
                        spawnPos.z += 0.01D;
                        int roleIndex = meta.getRoleIndex();
                        String nameKey = meta.getNpcNameKey();
                        HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] RELEASE roleIndex=%s npc=%s pos=%s face=%s", roleIndex, nameKey, spawnPos, face == null ? "null" : face.name());
                        NPCPlugin npcPlugin = NPCPlugin.get();
                        buffer.run((store) -> {
                            npcPlugin.spawnEntity(store, roleIndex, spawnPos, Vector3f.ZERO, (Model)null, (TriConsumer)null);
                        });
                        boolean consumed = ConsumeUtil.consumeActiveHotbarItem(player, held);
                        HytaleLogger.getLogger().at(Level.INFO).log("[TaleMon_PokeBall] RELEASE consume ok=%s", consumed);
                        context.getState().state = InteractionState.Finished;
                        return;
                    }
                }

                context.getState().state = InteractionState.Failed;
            } else {
                context.getState().state = InteractionState.Failed;
            }
        }
    }

    static {
        CODEC = ((Builder)BuilderCodec.builder(PokeBallReleaseInteraction.class, PokeBallReleaseInteraction::new, SimpleInstantInteraction.CODEC).documentation("Release a captured NPC from a Pok\u00e9Ball (consumes the ball).")).build();
    }
}
